### ISSUE TITLE
Multiple compilation errors

### ISSUE THREAD

**Issue by Lecrapouille** [Mars073/groupeA05#1]
Hello ! 

I have Code block 16.01 (debian 10) but I had plenty of compilation errors:
- Do not write `#include <Monster.h>` but `#include "Model/Monster.h"`<> are for system headers files. " " are for locals header files.
- Do not write `#include "Monster.h"` but `#include "Model/Monster.h"` since the makefile does not know where to locate files.
- Do not write `#include "iostream"` but `#include <iostream>` since they are system files.
- Idem for #include "btnAttack.h" => #include "View/Components/btnAttack.h", #include "FightManager.h" => #include "Model/FightManager.h"
- Linker errors: .o files are compiled obj/Debug/src/Model/GameMap.o but linker search them in obj/Debug/src/GameMap.o
- Object not compiled: Armor.o Bar.o ...

**Comment by Mars073** [comment]
Hello,
Thanks for the issue, I promise I'll make the changes after my term paper !

**Comment by Lecrapouille** [comment]
@Mars073 Good just one point: it looks like it is ` -std=c++2a` instead of `-std=c++20` at least for Debian g++ else it compiled well
